In [83]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [84]:
import os
import pandas as pd
import numpy as np

PROJECT_DIR = "/content/drive/MyDrive/Provider_Network_Project"

RAW_DIR = os.path.join(PROJECT_DIR, "data", "raw")
PROCESSED_DIR = os.path.join(PROJECT_DIR, "data", "processed")
GEOCODED_DIR = os.path.join(PROJECT_DIR, "data", "geocoded")
REFERENCE_DIR = os.path.join(PROJECT_DIR, "data", "reference")
OUTPUT_DIR = os.path.join(PROJECT_DIR, "outputs")

for folder in [
    RAW_DIR,
    PROCESSED_DIR,
    GEOCODED_DIR,
    REFERENCE_DIR,
    OUTPUT_DIR
]:
    os.makedirs(folder, exist_ok=True)

print("Project folders ready.")

Project folders ready.

In [85]:
NPPES_FILE = os.path.join(
    RAW_DIR,
    "nppes_sample_300000.csv"
)

print("Checking file...")
print(NPPES_FILE)

if os.path.exists(NPPES_FILE):
    size_gb = os.path.getsize(NPPES_FILE) / (1024 ** 3)
    size_mb = os.path.getsize(NPPES_FILE) / (1024 ** 2)

    print("✓ File found")
    print(f"File size: {size_mb:.2f} MB")
    print(f"File size: {size_gb:.2f} GB")
else:
    print("❌ File NOT found")
    print("Check that it is inside:")
    print(RAW_DIR)

Checking file...
/content/drive/MyDrive/Provider_Network_Project/data/raw/nppes_sample_300000.csv
✓ File found
File size: 160.22 MB
File size: 0.16 GB

In [86]:
print("Reading column names...")

columns = pd.read_csv(
    NPPES_FILE,
    nrows=0
).columns.tolist()

print("Number of columns:", len(columns))

print("\nFirst 30 columns:")
for i, col in enumerate(columns[:30], start=1):
    print(i, ":", col)

Reading column names...
Number of columns: 330

First 30 columns:
1 : NPI
2 : Entity Type Code
3 : Replacement NPI
4 : Employer Identification Number (EIN)
5 : Provider Organization Name (Legal Business Name)
6 : Provider Last Name (Legal Name)
7 : Provider First Name
8 : Provider Middle Name
9 : Provider Name Prefix Text
10 : Provider Name Suffix Text
11 : Provider Credential Text
12 : Provider Other Organization Name
13 : Provider Other Organization Name Type Code
14 : Provider Other Last Name
15 : Provider Other First Name
16 : Provider Other Middle Name
17 : Provider Other Name Prefix Text
18 : Provider Other Name Suffix Text
19 : Provider Other Credential Text
20 : Provider Other Last Name Type Code
21 : Provider First Line Business Mailing Address
22 : Provider Second Line Business Mailing Address
23 : Provider Business Mailing Address City Name
24 : Provider Business Mailing Address State Name
25 : Provider Business Mailing Address Postal Code
26 : Provider Business Mailing Address Country Code (If outside U.S.)
27 : Provider Business Mailing Address Telephone Number
28 : Provider Business Mailing Address Fax Number
29 : Provider First Line Business Practice Location Address
30 : Provider Second Line Business Practice Location Address

In [87]:
df_sample = pd.read_csv(
    NPPES_FILE,
    nrows=5,
    dtype=str
)

print("Columns:", len(df_sample.columns))
print("Preview shape:", df_sample.shape)

display(df_sample.head())

Columns: 330
Preview shape: (5, 330)

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,...,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15,Certification Date
0,1184627820,1,NaN,NaN,NaN,WEISS,CARL,B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/04/2023
1,1568460541,1,NaN,NaN,NaN,LONG,JOHN,P,NaN,JR.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1396729885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1174610372,2,NaN,<UNAVAIL>,"JULIE K. KUEKER, O.D., P.A.",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1013997535,1,NaN,NaN,NaN,SERVICE,MICHAEL,JAMES,MR.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
keywords = [
    "NPI",
    "Entity Type",
    "Provider First",
    "Provider Last",
    "Provider Organization",
    "Practice Location",
    "Taxonomy"
]

for keyword in keywords:
    print("\n" + "=" * 70)
    print(keyword)
    print("=" * 70)

    for col in columns:
        if keyword.lower() in col.lower():
            print(col)

======================================================================
NPI
======================================================================
NPI
Replacement NPI
NPI Deactivation Reason Code
NPI Deactivation Date
NPI Reactivation Date

======================================================================
Entity Type
======================================================================
Entity Type Code

======================================================================
Provider First
======================================================================
Provider First Name
Provider First Line Business Mailing Address
Provider First Line Business Practice Location Address

======================================================================
Provider Last
======================================================================
Provider Last Name (Legal Name)

======================================================================
Provider Organization
======================================================================
Provider Organization Name (Legal Business Name)

======================================================================
Practice Location
======================================================================
Provider First Line Business Practice Location Address
Provider Second Line Business Practice Location Address
Provider Business Practice Location Address City Name
Provider Business Practice Location Address State Name
Provider Business Practice Location Address Postal Code
Provider Business Practice Location Address Country Code (If outside U.S.)
Provider Business Practice Location Address Telephone Number
Provider Business Practice Location Address Fax Number

======================================================================
Taxonomy
======================================================================
Healthcare Provider Taxonomy Code_1
Healthcare Provider Primary Taxonomy Switch_1
Healthcare Provider Taxonomy Code_2
Healthcare Provider Primary Taxonomy Switch_2
Healthcare Provider Taxonomy Code_3
Healthcare Provider Primary Taxonomy Switch_3
Healthcare Provider Taxonomy Code_4
Healthcare Provider Primary Taxonomy Switch_4
Healthcare Provider Taxonomy Code_5
Healthcare Provider Primary Taxonomy Switch_5
Healthcare Provider Taxonomy Code_6
Healthcare Provider Primary Taxonomy Switch_6
Healthcare Provider Taxonomy Code_7
Healthcare Provider Primary Taxonomy Switch_7
Healthcare Provider Taxonomy Code_8
Healthcare Provider Primary Taxonomy Switch_8
Healthcare Provider Taxonomy Code_9
Healthcare Provider Primary Taxonomy Switch_9
Healthcare Provider Taxonomy Code_10
Healthcare Provider Primary Taxonomy Switch_10
Healthcare Provider Taxonomy Code_11
Healthcare Provider Primary Taxonomy Switch_11
Healthcare Provider Taxonomy Code_12
Healthcare Provider Primary Taxonomy Switch_12
Healthcare Provider Taxonomy Code_13
Healthcare Provider Primary Taxonomy Switch_13
Healthcare Provider Taxonomy Code_14
Healthcare Provider Primary Taxonomy Switch_14
Healthcare Provider Taxonomy Code_15
Healthcare Provider Primary Taxonomy Switch_15
Healthcare Provider Taxonomy Group_1
Healthcare Provider Taxonomy Group_2
Healthcare Provider Taxonomy Group_3
Healthcare Provider Taxonomy Group_4
Healthcare Provider Taxonomy Group_5
Healthcare Provider Taxonomy Group_6
Healthcare Provider Taxonomy Group_7
Healthcare Provider Taxonomy Group_8
Healthcare Provider Taxonomy Group_9
Healthcare Provider Taxonomy Group_10
Healthcare Provider Taxonomy Group_11
Healthcare Provider Taxonomy Group_12
Healthcare Provider Taxonomy Group_13
Healthcare Provider Taxonomy Group_14
Healthcare Provider Taxonomy Group_15

In [89]:
import pandas as pd
import numpy as np
import os

NPPES_FILE = "/content/drive/MyDrive/Provider_Network_Project/data/raw/nppes_sample_300000.csv"

df = pd.read_csv(
    NPPES_FILE,
    dtype=str,
    low_memory=False
)

print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 300000
Columns: 330

In [90]:
print("=" * 70)
print("NPPES DATASET INSPECTION")
print("=" * 70)

print("\nShape:")
print(df.shape)

print("\nDuplicate NPIs:")
print(df["NPI"].duplicated().sum())

print("\nEntity Type:")
print(df["Entity Type Code"].value_counts(dropna=False))

print("\nTop practice-location states:")
print(
    df[
        "Provider Business Practice Location Address State Name"
    ].value_counts(dropna=False).head(20)
)

======================================================================
NPPES DATASET INSPECTION
======================================================================

Shape:
(300000, 330)

Duplicate NPIs:
0

Entity Type:
Entity Type Code
1      234743
2       47019
NaN     18238
Name: count, dtype: int64

Top practice-location states:
Provider Business Practice Location Address State Name
CA     20107
TX     20077
FL     18555
NaN    18238
NY     17192
PA     16025
OH     12824
NC     10488
IL      8969
MI      8758
MA      8590
VA      7848
MN      7180
NJ      7086
GA      6884
IN      6442
AZ      6321
TN      6283
WA      5981
MD      5954
Name: count, dtype: int64

In [91]:
important_columns = [
    "NPI",
    "Entity Type Code",

    "Provider First Name",
    "Provider Last Name (Legal Name)",
    "Provider Organization Name (Legal Business Name)",

    "Provider First Line Business Practice Location Address",
    "Provider Second Line Business Practice Location Address",
    "Provider Business Practice Location Address City Name",
    "Provider Business Practice Location Address State Name",
    "Provider Business Practice Location Address Postal Code",
    "Provider Business Practice Location Address Telephone Number",

    "Healthcare Provider Taxonomy Code_1",
    "Healthcare Provider Primary Taxonomy Switch_1"
]

missing_report = pd.DataFrame({
    "column": important_columns,
    "missing_count": [
        df[col].isna().sum()
        for col in important_columns
    ]
})

missing_report["missing_percent"] = (
    missing_report["missing_count"]
    / len(df)
    * 100
)

missing_report

,column,missing_count,missing_percent
0,NPI,0,0.000000
1,Entity Type Code,18238,6.079333
2,Provider First Name,65257,21.752333
3,Provider Last Name (Legal Name),65260,21.753333
4,Provider Organization Name (Legal Business Name),252981,84.327000
5,Provider First Line Business Practice Location...,18238,6.079333
6,Provider Second Line Business Practice Locatio...,205340,68.446667
7,Provider Business Practice Location Address Ci...,18238,6.079333
8,Provider Business Practice Location Address St...,18238,6.079333
9,Provider Business Practice Location Address Po...,18238,6.079333
10,Provider Business Practice Location Address Te...,18253,6.084333
11,Healthcare Provider Taxonomy Code_1,18238,6.079333
12,Healthcare Provider Primary Taxonomy Switch_1,18238,6.079333

In [92]:
print("NPI missing:", df["NPI"].isna().sum())
print("NPI duplicates:", df["NPI"].duplicated().sum())

print("\nSample NPIs:")
display(df[["NPI"]].head(10))

NPI missing: 0
NPI duplicates: 0

Sample NPIs:

          NPI
0  1184627820
1  1568460541
2  1396729885
3  1174610372
4  1013997535
5  1932105079
6  1497713234
7  1083699102
8  1669472643
9  1437113537

In [93]:
ZIP_COL = "Provider Business Practice Location Address Postal Code"

df["ZIP_CLEAN"] = (
    df[ZIP_COL]
    .fillna("")
    .astype(str)
    .str.strip()
    .str[:5]
)

df["ZIP_CLEAN"] = (
    df["ZIP_CLEAN"]
    .where(
        df["ZIP_CLEAN"].str.match(r"^\d{5}$", na=False),
        np.nan
    )
)

print("Valid ZIP codes:")
print(df["ZIP_CLEAN"].notna().sum())

print("\nMissing/invalid ZIP codes:")
print(df["ZIP_CLEAN"].isna().sum())

Valid ZIP codes:
281727

Missing/invalid ZIP codes:
18273

In [94]:
STATE_COL = "Provider Business Practice Location Address State Name"

df["STATE_CLEAN"] = (
    df[STATE_COL]
    .fillna("")
    .astype(str)
    .str.strip()
    .str.upper()
)

print("States:")
print(df["STATE_CLEAN"].value_counts().head(20))

States:
STATE_CLEAN
CA    20107
TX    20077
FL    18555
      18238
NY    17192
PA    16025
OH    12824
NC    10488
IL     8969
MI     8758
MA     8590
VA     7848
MN     7180
NJ     7086
GA     6884
IN     6442
AZ     6321
TN     6283
WA     5981
MD     5954
Name: count, dtype: int64

In [95]:
df["GEOSPATIAL_READY"] = (
    df["NPI"].notna()
    & df["NPI"].ne("")
    & df["STATE_CLEAN"].notna()
    & df["STATE_CLEAN"].ne("")
    & df["ZIP_CLEAN"].notna()
)

print(
    df["GEOSPATIAL_READY"]
    .value_counts()
)

GEOSPATIAL_READY
True     281727
False     18273
Name: count, dtype: int64

In [96]:
taxonomy_columns = [
    f"Healthcare Provider Taxonomy Code_{i}"
    for i in range(1, 16)
]

for col in taxonomy_columns:

    if col in df.columns:

        non_missing = df[col].notna().sum()

        print(
            f"{col}: "
            f"{non_missing:,} non-missing"
        )

Healthcare Provider Taxonomy Code_1: 281,762 non-missing
Healthcare Provider Taxonomy Code_2: 68,400 non-missing
Healthcare Provider Taxonomy Code_3: 21,275 non-missing
Healthcare Provider Taxonomy Code_4: 8,110 non-missing
Healthcare Provider Taxonomy Code_5: 3,910 non-missing
Healthcare Provider Taxonomy Code_6: 2,223 non-missing
Healthcare Provider Taxonomy Code_7: 1,427 non-missing
Healthcare Provider Taxonomy Code_8: 1,014 non-missing
Healthcare Provider Taxonomy Code_9: 694 non-missing
Healthcare Provider Taxonomy Code_10: 543 non-missing
Healthcare Provider Taxonomy Code_11: 424 non-missing
Healthcare Provider Taxonomy Code_12: 343 non-missing
Healthcare Provider Taxonomy Code_13: 266 non-missing
Healthcare Provider Taxonomy Code_14: 222 non-missing
Healthcare Provider Taxonomy Code_15: 160 non-missing

In [97]:
primary_switch_columns = [
    f"Healthcare Provider Primary Taxonomy Switch_{i}"
    for i in range(1, 16)
]

for col in primary_switch_columns:

    if col in df.columns:

        print(
            f"\n{col}"
        )

        print(
            df[col]
            .value_counts(dropna=False)
        )

Healthcare Provider Primary Taxonomy Switch_1
Healthcare Provider Primary Taxonomy Switch_1
Y      232355
N       49407
NaN     18238
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_2
Healthcare Provider Primary Taxonomy Switch_2
NaN    231600
Y       36175
N       32225
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_3
Healthcare Provider Primary Taxonomy Switch_3
NaN    278725
N       12377
Y        8898
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_4
Healthcare Provider Primary Taxonomy Switch_4
NaN    291890
N        5574
Y        2536
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_5
Healthcare Provider Primary Taxonomy Switch_5
NaN    296090
N        3015
Y         895
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_6
Healthcare Provider Primary Taxonomy Switch_6
NaN    297777
N        1825
Y         398
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_7
Healthcare Provider Primary Taxonomy Switch_7
NaN    298573
N        1247
Y         180
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_8
Healthcare Provider Primary Taxonomy Switch_8
NaN    298986
N         896
Y         118
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_9
Healthcare Provider Primary Taxonomy Switch_9
NaN    299306
N         646
Y          48
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_10
Healthcare Provider Primary Taxonomy Switch_10
NaN    299457
N         501
Y          42
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_11
Healthcare Provider Primary Taxonomy Switch_11
NaN    299576
N         387
Y          37
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_12
Healthcare Provider Primary Taxonomy Switch_12
NaN    299657
N         316
Y          27
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_13
Healthcare Provider Primary Taxonomy Switch_13
NaN    299734
N         247
Y          19
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_14
Healthcare Provider Primary Taxonomy Switch_14
NaN    299778
N         206
Y          16
Name: count, dtype: int64

Healthcare Provider Primary Taxonomy Switch_15
Healthcare Provider Primary Taxonomy Switch_15
NaN    299840
N         142
Y          18
Name: count, dtype: int64

In [98]:
df["PRIMARY_TAXONOMY"] = np.nan

for i in range(1, 16):

    taxonomy_col = (
        f"Healthcare Provider Taxonomy Code_{i}"
    )

    switch_col = (
        f"Healthcare Provider Primary Taxonomy Switch_{i}"
    )

    if (
        taxonomy_col in df.columns
        and switch_col in df.columns
    ):

        mask = (
            df["PRIMARY_TAXONOMY"].isna()
            & df[switch_col].fillna("").eq("Y")
            & df[taxonomy_col].notna()
            & df[taxonomy_col].ne("")
        )

        df.loc[
            mask,
            "PRIMARY_TAXONOMY"
        ] = df.loc[
            mask,
            taxonomy_col
        ]

# Fallback:
# If no Y flag was found, use Taxonomy Code 1
fallback_mask = (
    df["PRIMARY_TAXONOMY"].isna()
    & df["Healthcare Provider Taxonomy Code_1"].notna()
    & df["Healthcare Provider Taxonomy Code_1"].ne("")
)

df.loc[
    fallback_mask,
    "PRIMARY_TAXONOMY"
] = df.loc[
    fallback_mask,
    "Healthcare Provider Taxonomy Code_1"
]

print(
    "Primary taxonomy available:",
    df["PRIMARY_TAXONOMY"].notna().sum()
)

print(
    "\nTop taxonomy codes:"
)

print(
    df["PRIMARY_TAXONOMY"]
    .value_counts()
    .head(20)
)

/tmp/ipykernel_574/2378457667.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['208800000X' '152W00000X' '363LF0000X' ... '231H00000X' '208600000X'
 '111N00000X']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[

Primary taxonomy available: 281762

Top taxonomy codes:
PRIMARY_TAXONOMY
207Q00000X    20367
207R00000X    16451
208000000X     8761
207L00000X     8511
225100000X     8054
2085R0202X     7655
1223G0001X     6520
152W00000X     6384
111N00000X     6304
207V00000X     6161
207P00000X     6125
367500000X     6043
174400000X     5746
363A00000X     5481
207RC0000X     5019
1041C0700X     4715
207W00000X     4615
363LF0000X     4359
208600000X     4358
207X00000X     4345
Name: count, dtype: int64

In [99]:
df["PROVIDER_TYPE"] = (
    df["Entity Type Code"]
    .map({
        "1": "Individual",
        "2": "Organization"
    })
    .fillna("Unknown")
)

print(
    df["PROVIDER_TYPE"]
    .value_counts()
)

PROVIDER_TYPE
Individual      234743
Organization     47019
Unknown          18238
Name: count, dtype: int64

In [100]:
df["ADDRESS_READY"] = (
    df[
        "Provider First Line Business Practice Location Address"
    ].fillna("").ne("")
    &
    df[
        "Provider Business Practice Location Address City Name"
    ].fillna("").ne("")
    &
    df["STATE_CLEAN"].ne("")
    &
    df["ZIP_CLEAN"].notna()
)

print(
    df["ADDRESS_READY"]
    .value_counts()
)

ADDRESS_READY
True     281727
False     18273
Name: count, dtype: int64

In [101]:
CLEAN_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/"
    "data/processed/"
    "provider_clean_300000.csv"
)

df.to_csv(
    CLEAN_FILE,
    index=False
)

print("Saved successfully:")
print(CLEAN_FILE)

print("\nFinal shape:")
print(df.shape)

Saved successfully:
/content/drive/MyDrive/Provider_Network_Project/data/processed/provider_clean_300000.csv

Final shape:
(300000, 336)

In [102]:
# ============================================================
# GEOSPATIAL PREPARATION - INSPECTION
# ============================================================

import pandas as pd
import numpy as np

CLEAN_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/"
    "data/processed/"
    "provider_clean_300000.csv"
)

df = pd.read_csv(
    CLEAN_FILE,
    dtype=str,
    low_memory=False
)

print("=" * 70)
print("GEOSPATIAL PREPARATION")
print("=" * 70)

print("\nDataset shape:")
print(df.shape)

# ------------------------------------------------------------
# Address columns
# ------------------------------------------------------------

address_columns = [
    "Provider First Line Business Practice Location Address",
    "Provider Second Line Business Practice Location Address",
    "Provider Business Practice Location Address City Name",
    "Provider Business Practice Location Address State Name",
    "Provider Business Practice Location Address Postal Code"
]

print("\nAddress missingness:")

for col in address_columns:
    missing = df[col].isna().sum()
    percentage = missing / len(df) * 100

    print(
        f"{col}: "
        f"{missing:,} missing "
        f"({percentage:.2f}%)"
    )

# ------------------------------------------------------------
# Geospatial eligibility
# ------------------------------------------------------------

print("\nGEOSPATIAL_READY distribution:")
print(
    df["GEOSPATIAL_READY"]
    .value_counts(dropna=False)
)

print("\nADDRESS_READY distribution:")
print(
    df["ADDRESS_READY"]
    .value_counts(dropna=False)
)

# ------------------------------------------------------------
# Unique ZIPs
# ------------------------------------------------------------

print("\nUnique ZIP codes:")

unique_zips = (
    df.loc[
        df["ZIP_CLEAN"].notna(),
        "ZIP_CLEAN"
    ]
    .nunique()
)

print(unique_zips)

# ------------------------------------------------------------
# Unique state + ZIP combinations
# ------------------------------------------------------------

unique_state_zip = (
    df.loc[
        df["GEOSPATIAL_READY"] == True,
        ["STATE_CLEAN", "ZIP_CLEAN"]
    ]
    .drop_duplicates()
    .shape[0]
)

print(
    "\nUnique State + ZIP combinations:",
    unique_state_zip
)

# ------------------------------------------------------------
# Exact address uniqueness
# ------------------------------------------------------------

geo_df = df[
    df["GEOSPATIAL_READY"] == True
].copy()

geo_df["ADDRESS_KEY"] = (
    geo_df[
        "Provider First Line Business Practice Location Address"
    ]
    .fillna("")
    .str.upper()
    .str.strip()
    + "|"
    +
    geo_df[
        "Provider Business Practice Location Address City Name"
    ]
    .fillna("")
    .str.upper()
    .str.strip()
    + "|"
    +
    geo_df["STATE_CLEAN"]
    + "|"
    +
    geo_df["ZIP_CLEAN"]
)

unique_addresses = (
    geo_df["ADDRESS_KEY"]
    .nunique()
)

print(
    "\nProviders with usable geography:",
    f"{len(geo_df):,}"
)

print(
    "Unique practice addresses:",
    f"{unique_addresses:,}"
)

print(
    "\nPotential geocoding reduction:",
    f"{len(geo_df) - unique_addresses:,}",
    "duplicate address occurrences"
)

======================================================================
GEOSPATIAL PREPARATION
======================================================================

Dataset shape:
(300000, 336)

Address missingness:
Provider First Line Business Practice Location Address: 18,238 missing (6.08%)
Provider Second Line Business Practice Location Address: 205,340 missing (68.45%)
Provider Business Practice Location Address City Name: 18,238 missing (6.08%)
Provider Business Practice Location Address State Name: 18,238 missing (6.08%)
Provider Business Practice Location Address Postal Code: 18,238 missing (6.08%)

GEOSPATIAL_READY distribution:
GEOSPATIAL_READY
True     281727
False     18273
Name: count, dtype: int64

ADDRESS_READY distribution:
ADDRESS_READY
True     281727
False     18273
Name: count, dtype: int64

Unique ZIP codes:
16825

Unique State + ZIP combinations: 0

Providers with usable geography: 0
Unique practice addresses: 0

Potential geocoding reduction: 0 duplicate address occurrences

In [103]:
# ============================================================
# FIX GEOSPATIAL INSPECTION
# ============================================================

# Convert GEOSPATIAL_READY from string to real boolean
df["GEOSPATIAL_READY_BOOL"] = (
    df["GEOSPATIAL_READY"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
)

df["ADDRESS_READY_BOOL"] = (
    df["ADDRESS_READY"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
)

# ------------------------------------------------------------
# Providers with usable geography
# ------------------------------------------------------------

geo_df = df[
    df["GEOSPATIAL_READY_BOOL"]
].copy()

print("=" * 70)
print("CORRECTED GEOSPATIAL INSPECTION")
print("=" * 70)

print(
    "\nProviders with usable geography:",
    f"{len(geo_df):,}"
)

# ------------------------------------------------------------
# Unique ZIP codes
# ------------------------------------------------------------

unique_zips = (
    geo_df["ZIP_CLEAN"]
    .dropna()
    .nunique()
)

print(
    "Unique ZIP codes:",
    f"{unique_zips:,}"
)

# ------------------------------------------------------------
# Unique STATE + ZIP
# ------------------------------------------------------------

unique_state_zip = (
    geo_df[
        ["STATE_CLEAN", "ZIP_CLEAN"]
    ]
    .dropna()
    .drop_duplicates()
    .shape[0]
)

print(
    "Unique State + ZIP combinations:",
    f"{unique_state_zip:,}"
)

# ------------------------------------------------------------
# Create address key
# ------------------------------------------------------------

geo_df["ADDRESS_KEY"] = (
    geo_df[
        "Provider First Line Business Practice Location Address"
    ]
    .fillna("")
    .astype(str)
    .str.upper()
    .str.strip()
    + "|"
    +
    geo_df[
        "Provider Business Practice Location Address City Name"
    ]
    .fillna("")
    .astype(str)
    .str.upper()
    .str.strip()
    + "|"
    +
    geo_df["STATE_CLEAN"]
    .fillna("")
    .astype(str)
    .str.upper()
    .str.strip()
    + "|"
    +
    geo_df["ZIP_CLEAN"]
    .fillna("")
    .astype(str)
    .str.strip()
)

unique_addresses = (
    geo_df["ADDRESS_KEY"]
    .nunique()
)

print(
    "Unique practice addresses:",
    f"{unique_addresses:,}"
)

# ------------------------------------------------------------
# Duplicate address occurrences
# ------------------------------------------------------------

duplicate_address_occurrences = (
    len(geo_df) - unique_addresses
)

print(
    "Duplicate address occurrences:",
    f"{duplicate_address_occurrences:,}"
)

# ------------------------------------------------------------
# State distribution
# ------------------------------------------------------------

print("\nTop states:")

print(
    geo_df["STATE_CLEAN"]
    .value_counts()
    .head(20)
)

# ------------------------------------------------------------
# ZIP distribution
# ------------------------------------------------------------

print("\nTop ZIP codes:")

print(
    geo_df["ZIP_CLEAN"]
    .value_counts()
    .head(20)
)

======================================================================
CORRECTED GEOSPATIAL INSPECTION
======================================================================

Providers with usable geography: 281,727
Unique ZIP codes: 16,825
Unique State + ZIP combinations: 16,934
Unique practice addresses: 156,330
Duplicate address occurrences: 125,397

Top states:
STATE_CLEAN
CA    20107
TX    20077
FL    18555
NY    17192
PA    16025
OH    12824
NC    10488
IL     8969
MI     8758
MA     8590
VA     7848
MN     7180
NJ     7086
GA     6884
IN     6442
AZ     6321
TN     6283
WA     5981
MD     5954
MO     5667
Name: count, dtype: int64

Top ZIP codes:
ZIP_CLEAN
55905    1156
44195     577
95817     566
54601     566
77030     554
02115     463
02114     455
78229     423
37203     404
27103     401
10021     401
27157     398
46202     395
75390     364
55435     322
30342     317
02118     314
76104     312
27834     308
15212     288
Name: count, dtype: int64

In [104]:
# ============================================================
# ML-1 GEOSPATIAL FEATURE ENGINEERING
# ZIP / STATE LEVEL
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("BUILDING GEOSPATIAL PROVIDER FEATURES")
print("=" * 70)

# ------------------------------------------------------------
# Make sure geography flags are boolean
# ------------------------------------------------------------

df["GEOSPATIAL_READY_BOOL"] = (
    df["GEOSPATIAL_READY"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
)

# ------------------------------------------------------------
# Keep providers with usable geography
# ------------------------------------------------------------

geo_df = df[
    df["GEOSPATIAL_READY_BOOL"]
].copy()

print(
    "Providers entering geographic feature engineering:",
    f"{len(geo_df):,}"
)

# ------------------------------------------------------------
# Clean state / ZIP
# ------------------------------------------------------------

geo_df["STATE_CLEAN"] = (
    geo_df["STATE_CLEAN"]
    .astype(str)
    .str.strip()
    .str.upper()
)

geo_df["ZIP_CLEAN"] = (
    geo_df["ZIP_CLEAN"]
    .astype(str)
    .str.strip()
)

# ------------------------------------------------------------
# Create geographic key
# ------------------------------------------------------------

geo_df["GEO_KEY"] = (
    geo_df["STATE_CLEAN"]
    + "_"
    + geo_df["ZIP_CLEAN"]
)

# ------------------------------------------------------------
# Provider count
# ------------------------------------------------------------

provider_count = (
    geo_df
    .groupby(
        ["STATE_CLEAN", "ZIP_CLEAN"],
        as_index=False
    )
    .agg(
        provider_count=("NPI", "nunique")
    )
)

print(
    "\nGeographic areas created:",
    f"{len(provider_count):,}"
)

print("\nSample:")
print(provider_count.head(10))

======================================================================
BUILDING GEOSPATIAL PROVIDER FEATURES
======================================================================
Providers entering geographic feature engineering: 281,727

Geographic areas created: 16,934

Sample:
  STATE_CLEAN ZIP_CLEAN  provider_count
0          AA     20889               2
1          AA     34009               1
2          AA     34031               2
3          AA     34039               1
4          AA     34092               1
5          AA     34093               1
6          AA     80913               1
7          AA     92055               1
8          AE     00000               1
9          AE     09009               1

In [105]:
# ============================================================
# PROVIDER TYPE FEATURES
# ============================================================

provider_type_features = (
    geo_df
    .pivot_table(
        index=["STATE_CLEAN", "ZIP_CLEAN"],
        columns="PROVIDER_TYPE",
        values="NPI",
        aggfunc="nunique",
        fill_value=0
    )
    .reset_index()
)

# Rename columns safely
provider_type_features = provider_type_features.rename(
    columns={
        "Individual": "individual_provider_count",
        "Organization": "organization_provider_count",
        "Unknown": "unknown_provider_count"
    }
)

print("=" * 70)
print("PROVIDER TYPE FEATURES")
print("=" * 70)

print(provider_type_features.head())

======================================================================
PROVIDER TYPE FEATURES
======================================================================
PROVIDER_TYPE STATE_CLEAN ZIP_CLEAN  individual_provider_count  \
0                      AA     20889                          2
1                      AA     34009                          1
2                      AA     34031                          2
3                      AA     34039                          1
4                      AA     34092                          1

PROVIDER_TYPE  organization_provider_count
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0

In [106]:
# ============================================================
# SPECIALTY FEATURES
# ============================================================

specialty_features = (
    geo_df
    .groupby(
        ["STATE_CLEAN", "ZIP_CLEAN"],
        as_index=False
    )
    .agg(
        unique_specialty_count=(
            "PRIMARY_TAXONOMY",
            lambda x: x.dropna().nunique()
        ),
        providers_with_specialty=(
            "PRIMARY_TAXONOMY",
            lambda x: x.notna().sum()
        )
    )
)

print("=" * 70)
print("SPECIALTY FEATURES")
print("=" * 70)

print(specialty_features.head(10))

======================================================================
SPECIALTY FEATURES
======================================================================
  STATE_CLEAN ZIP_CLEAN  unique_specialty_count  providers_with_specialty
0          AA     20889                       2                         2
1          AA     34009                       1                         1
2          AA     34031                       2                         2
3          AA     34039                       1                         1
4          AA     34092                       1                         1
5          AA     34093                       1                         1
6          AA     80913                       1                         1
7          AA     92055                       1                         1
8          AE     00000                       1                         1
9          AE     09009                       1                         1

In [107]:
print(geo_df.columns.tolist())

['NPI', 'Entity Type Code', 'Replacement NPI', 'Employer Identification Number (EIN)', 'Provider Organization Name (Legal Business Name)', 'Provider Last Name (Legal Name)', 'Provider First Name', 'Provider Middle Name', 'Provider Name Prefix Text', 'Provider Name Suffix Text', 'Provider Credential Text', 'Provider Other Organization Name', 'Provider Other Organization Name Type Code', 'Provider Other Last Name', 'Provider Other First Name', 'Provider Other Middle Name', 'Provider Other Name Prefix Text', 'Provider Other Name Suffix Text', 'Provider Other Credential Text', 'Provider Other Last Name Type Code', 'Provider First Line Business Mailing Address', 'Provider Second Line Business Mailing Address', 'Provider Business Mailing Address City Name', 'Provider Business Mailing Address State Name', 'Provider Business Mailing Address Postal Code', 'Provider Business Mailing Address Country Code (If outside U.S.)', 'Provider Business Mailing Address Telephone Number', 'Provider Business Mailing Address Fax Number', 'Provider First Line Business Practice Location Address', 'Provider Second Line Business Practice Location Address', 'Provider Business Practice Location Address City Name', 'Provider Business Practice Location Address State Name', 'Provider Business Practice Location Address Postal Code', 'Provider Business Practice Location Address Country Code (If outside U.S.)', 'Provider Business Practice Location Address Telephone Number', 'Provider Business Practice Location Address Fax Number', 'Provider Enumeration Date', 'Last Update Date', 'NPI Deactivation Reason Code', 'NPI Deactivation Date', 'NPI Reactivation Date', 'Provider Sex Code', 'Authorized Official Last Name', 'Authorized Official First Name', 'Authorized Official Middle Name', 'Authorized Official Title or Position', 'Authorized Official Telephone Number', 'Healthcare Provider Taxonomy Code_1', 'Provider License Number_1', 'Provider License Number State Code_1', 'Healthcare Provider Primary Taxonomy Switch_1', 'Healthcare Provider Taxonomy Code_2', 'Provider License Number_2', 'Provider License Number State Code_2', 'Healthcare Provider Primary Taxonomy Switch_2', 'Healthcare Provider Taxonomy Code_3', 'Provider License Number_3', 'Provider License Number State Code_3', 'Healthcare Provider Primary Taxonomy Switch_3', 'Healthcare Provider Taxonomy Code_4', 'Provider License Number_4', 'Provider License Number State Code_4', 'Healthcare Provider Primary Taxonomy Switch_4', 'Healthcare Provider Taxonomy Code_5', 'Provider License Number_5', 'Provider License Number State Code_5', 'Healthcare Provider Primary Taxonomy Switch_5', 'Healthcare Provider Taxonomy Code_6', 'Provider License Number_6', 'Provider License Number State Code_6', 'Healthcare Provider Primary Taxonomy Switch_6', 'Healthcare Provider Taxonomy Code_7', 'Provider License Number_7', 'Provider License Number State Code_7', 'Healthcare Provider Primary Taxonomy Switch_7', 'Healthcare Provider Taxonomy Code_8', 'Provider License Number_8', 'Provider License Number State Code_8', 'Healthcare Provider Primary Taxonomy Switch_8', 'Healthcare Provider Taxonomy Code_9', 'Provider License Number_9', 'Provider License Number State Code_9', 'Healthcare Provider Primary Taxonomy Switch_9', 'Healthcare Provider Taxonomy Code_10', 'Provider License Number_10', 'Provider License Number State Code_10', 'Healthcare Provider Primary Taxonomy Switch_10', 'Healthcare Provider Taxonomy Code_11', 'Provider License Number_11', 'Provider License Number State Code_11', 'Healthcare Provider Primary Taxonomy Switch_11', 'Healthcare Provider Taxonomy Code_12', 'Provider License Number_12', 'Provider License Number State Code_12', 'Healthcare Provider Primary Taxonomy Switch_12', 'Healthcare Provider Taxonomy Code_13', 'Provider License Number_13', 'Provider License Number State Code_13', 'Healthcare Provider Primary Taxonomy Switch_13', 'Healthcare Provider Taxonomy Code_14', 'Provider License Number_14', 'Provider License Number State Code_14', 'Healthcare Provider Primary Taxonomy Switch_14', 'Healthcare Provider Taxonomy Code_15', 'Provider License Number_15', 'Provider License Number State Code_15', 'Healthcare Provider Primary Taxonomy Switch_15', 'Other Provider Identifier_1', 'Other Provider Identifier Type Code_1', 'Other Provider Identifier State_1', 'Other Provider Identifier Issuer_1', 'Other Provider Identifier_2', 'Other Provider Identifier Type Code_2', 'Other Provider Identifier State_2', 'Other Provider Identifier Issuer_2', 'Other Provider Identifier_3', 'Other Provider Identifier Type Code_3', 'Other Provider Identifier State_3', 'Other Provider Identifier Issuer_3', 'Other Provider Identifier_4', 'Other Provider Identifier Type Code_4', 'Other Provider Identifier State_4', 'Other Provider Identifier Issuer_4', 'Other Provider Identifier_5', 'Other Provider Identifier Type Code_5', 'Other Provider Identifier State_5', 'Other Provider Identifier Issuer_5', 'Other Provider Identifier_6', 'Other Provider Identifier Type Code_6', 'Other Provider Identifier State_6', 'Other Provider Identifier Issuer_6', 'Other Provider Identifier_7', 'Other Provider Identifier Type Code_7', 'Other Provider Identifier State_7', 'Other Provider Identifier Issuer_7', 'Other Provider Identifier_8', 'Other Provider Identifier Type Code_8', 'Other Provider Identifier State_8', 'Other Provider Identifier Issuer_8', 'Other Provider Identifier_9', 'Other Provider Identifier Type Code_9', 'Other Provider Identifier State_9', 'Other Provider Identifier Issuer_9', 'Other Provider Identifier_10', 'Other Provider Identifier Type Code_10', 'Other Provider Identifier State_10', 'Other Provider Identifier Issuer_10', 'Other Provider Identifier_11', 'Other Provider Identifier Type Code_11', 'Other Provider Identifier State_11', 'Other Provider Identifier Issuer_11', 'Other Provider Identifier_12', 'Other Provider Identifier Type Code_12', 'Other Provider Identifier State_12', 'Other Provider Identifier Issuer_12', 'Other Provider Identifier_13', 'Other Provider Identifier Type Code_13', 'Other Provider Identifier State_13', 'Other Provider Identifier Issuer_13', 'Other Provider Identifier_14', 'Other Provider Identifier Type Code_14', 'Other Provider Identifier State_14', 'Other Provider Identifier Issuer_14', 'Other Provider Identifier_15', 'Other Provider Identifier Type Code_15', 'Other Provider Identifier State_15', 'Other Provider Identifier Issuer_15', 'Other Provider Identifier_16', 'Other Provider Identifier Type Code_16', 'Other Provider Identifier State_16', 'Other Provider Identifier Issuer_16', 'Other Provider Identifier_17', 'Other Provider Identifier Type Code_17', 'Other Provider Identifier State_17', 'Other Provider Identifier Issuer_17', 'Other Provider Identifier_18', 'Other Provider Identifier Type Code_18', 'Other Provider Identifier State_18', 'Other Provider Identifier Issuer_18', 'Other Provider Identifier_19', 'Other Provider Identifier Type Code_19', 'Other Provider Identifier State_19', 'Other Provider Identifier Issuer_19', 'Other Provider Identifier_20', 'Other Provider Identifier Type Code_20', 'Other Provider Identifier State_20', 'Other Provider Identifier Issuer_20', 'Other Provider Identifier_21', 'Other Provider Identifier Type Code_21', 'Other Provider Identifier State_21', 'Other Provider Identifier Issuer_21', 'Other Provider Identifier_22', 'Other Provider Identifier Type Code_22', 'Other Provider Identifier State_22', 'Other Provider Identifier Issuer_22', 'Other Provider Identifier_23', 'Other Provider Identifier Type Code_23', 'Other Provider Identifier State_23', 'Other Provider Identifier Issuer_23', 'Other Provider Identifier_24', 'Other Provider Identifier Type Code_24', 'Other Provider Identifier State_24', 'Other Provider Identifier Issuer_24', 'Other Provider Identifier_25', 'Other Provider Identifier Type Code_25', 'Other Provider Identifier State_25', 'Other Provider Identifier Issuer_25', 'Other Provider Identifier_26', 'Other Provider Identifier Type Code_26', 'Other Provider Identifier State_26', 'Other Provider Identifier Issuer_26', 'Other Provider Identifier_27', 'Other Provider Identifier Type Code_27', 'Other Provider Identifier State_27', 'Other Provider Identifier Issuer_27', 'Other Provider Identifier_28', 'Other Provider Identifier Type Code_28', 'Other Provider Identifier State_28', 'Other Provider Identifier Issuer_28', 'Other Provider Identifier_29', 'Other Provider Identifier Type Code_29', 'Other Provider Identifier State_29', 'Other Provider Identifier Issuer_29', 'Other Provider Identifier_30', 'Other Provider Identifier Type Code_30', 'Other Provider Identifier State_30', 'Other Provider Identifier Issuer_30', 'Other Provider Identifier_31', 'Other Provider Identifier Type Code_31', 'Other Provider Identifier State_31', 'Other Provider Identifier Issuer_31', 'Other Provider Identifier_32', 'Other Provider Identifier Type Code_32', 'Other Provider Identifier State_32', 'Other Provider Identifier Issuer_32', 'Other Provider Identifier_33', 'Other Provider Identifier Type Code_33', 'Other Provider Identifier State_33', 'Other Provider Identifier Issuer_33', 'Other Provider Identifier_34', 'Other Provider Identifier Type Code_34', 'Other Provider Identifier State_34', 'Other Provider Identifier Issuer_34', 'Other Provider Identifier_35', 'Other Provider Identifier Type Code_35', 'Other Provider Identifier State_35', 'Other Provider Identifier Issuer_35', 'Other Provider Identifier_36', 'Other Provider Identifier Type Code_36', 'Other Provider Identifier State_36', 'Other Provider Identifier Issuer_36', 'Other Provider Identifier_37', 'Other Provider Identifier Type Code_37', 'Other Provider Identifier State_37', 'Other Provider Identifier Issuer_37', 'Other Provider Identifier_38', 'Other Provider Identifier Type Code_38', 'Other Provider Identifier State_38', 'Other Provider Identifier Issuer_38', 'Other Provider Identifier_39', 'Other Provider Identifier Type Code_39', 'Other Provider Identifier State_39', 'Other Provider Identifier Issuer_39', 'Other Provider Identifier_40', 'Other Provider Identifier Type Code_40', 'Other Provider Identifier State_40', 'Other Provider Identifier Issuer_40', 'Other Provider Identifier_41', 'Other Provider Identifier Type Code_41', 'Other Provider Identifier State_41', 'Other Provider Identifier Issuer_41', 'Other Provider Identifier_42', 'Other Provider Identifier Type Code_42', 'Other Provider Identifier State_42', 'Other Provider Identifier Issuer_42', 'Other Provider Identifier_43', 'Other Provider Identifier Type Code_43', 'Other Provider Identifier State_43', 'Other Provider Identifier Issuer_43', 'Other Provider Identifier_44', 'Other Provider Identifier Type Code_44', 'Other Provider Identifier State_44', 'Other Provider Identifier Issuer_44', 'Other Provider Identifier_45', 'Other Provider Identifier Type Code_45', 'Other Provider Identifier State_45', 'Other Provider Identifier Issuer_45', 'Other Provider Identifier_46', 'Other Provider Identifier Type Code_46', 'Other Provider Identifier State_46', 'Other Provider Identifier Issuer_46', 'Other Provider Identifier_47', 'Other Provider Identifier Type Code_47', 'Other Provider Identifier State_47', 'Other Provider Identifier Issuer_47', 'Other Provider Identifier_48', 'Other Provider Identifier Type Code_48', 'Other Provider Identifier State_48', 'Other Provider Identifier Issuer_48', 'Other Provider Identifier_49', 'Other Provider Identifier Type Code_49', 'Other Provider Identifier State_49', 'Other Provider Identifier Issuer_49', 'Other Provider Identifier_50', 'Other Provider Identifier Type Code_50', 'Other Provider Identifier State_50', 'Other Provider Identifier Issuer_50', 'Is Sole Proprietor', 'Is Organization Subpart', 'Parent Organization LBN', 'Parent Organization TIN', 'Authorized Official Name Prefix Text', 'Authorized Official Name Suffix Text', 'Authorized Official Credential Text', 'Healthcare Provider Taxonomy Group_1', 'Healthcare Provider Taxonomy Group_2', 'Healthcare Provider Taxonomy Group_3', 'Healthcare Provider Taxonomy Group_4', 'Healthcare Provider Taxonomy Group_5', 'Healthcare Provider Taxonomy Group_6', 'Healthcare Provider Taxonomy Group_7', 'Healthcare Provider Taxonomy Group_8', 'Healthcare Provider Taxonomy Group_9', 'Healthcare Provider Taxonomy Group_10', 'Healthcare Provider Taxonomy Group_11', 'Healthcare Provider Taxonomy Group_12', 'Healthcare Provider Taxonomy Group_13', 'Healthcare Provider Taxonomy Group_14', 'Healthcare Provider Taxonomy Group_15', 'Certification Date', 'ZIP_CLEAN', 'STATE_CLEAN', 'GEOSPATIAL_READY', 'PRIMARY_TAXONOMY', 'PROVIDER_TYPE', 'ADDRESS_READY', 'GEOSPATIAL_READY_BOOL', 'ADDRESS_READY_BOOL', 'GEO_KEY']

In [108]:
# ============================================================
# ZIP + SPECIALTY LEVEL FEATURES
# ============================================================

area_specialty_features = (
    geo_df
    .dropna(subset=["PRIMARY_TAXONOMY"])
    .groupby(
        ["STATE_CLEAN", "ZIP_CLEAN", "PRIMARY_TAXONOMY"],
        as_index=False
    )
    .agg(
        specialty_provider_count=(
            "NPI",
            "nunique"
        )
    )
)

print("=" * 70)
print("ZIP + SPECIALTY LEVEL FEATURES")
print("=" * 70)

print(area_specialty_features.head(20))
print("\nShape:", area_specialty_features.shape)

======================================================================
ZIP + SPECIALTY LEVEL FEATURES
======================================================================
   STATE_CLEAN ZIP_CLEAN PRIMARY_TAXONOMY  specialty_provider_count
0           AA     20889       103G00000X                         1
1           AA     20889       208600000X                         1
2           AA     34009       207Q00000X                         1
3           AA     34031       207R00000X                         1
4           AA     34031       2083P0901X                         1
5           AA     34039       363AM0700X                         1
6           AA     34092       1710I1002X                         1
7           AA     34093       1710I1002X                         1
8           AA     80913       207P00000X                         1
9           AA     92055       207Q00000X                         1
10          AE     00000       363A00000X                         1
11          AE     09009       363AM0700X                         1
12          AE     09012       1223G0001X                         1
13          AE     09031       171W00000X                         1
14          AE     09031       363LF0000X                         1
15          AE     09033       1041C0700X                         1
16          AE     09033       152W00000X                         1
17          AE     09034       152WP0200X                         1
18          AE     09036       2084P0800X                         1
19          AE     09042       103TC0700X                         1

Shape: (165068, 4)

In [109]:
# ============================================================
# MERGE GEOGRAPHIC FEATURES
# ============================================================

geo_features = provider_count.merge(
    provider_type_features,
    on=["STATE_CLEAN", "ZIP_CLEAN"],
    how="left"
)

geo_features = geo_features.merge(
    specialty_features,
    on=["STATE_CLEAN", "ZIP_CLEAN"],
    how="left"
)

print("=" * 70)
print("MERGED GEOSPATIAL FEATURES")
print("=" * 70)

print("Shape:", geo_features.shape)

print("\nColumns:")
print(geo_features.columns.tolist())

print("\nPreview:")
display(geo_features.head(10))

======================================================================
MERGED GEOSPATIAL FEATURES
======================================================================
Shape: (16934, 7)

Columns:
['STATE_CLEAN', 'ZIP_CLEAN', 'provider_count', 'individual_provider_count', 'organization_provider_count', 'unique_specialty_count', 'providers_with_specialty']

Preview:

,STATE_CLEAN,ZIP_CLEAN,provider_count,individual_provider_count,organization_provider_count,unique_specialty_count,providers_with_specialty
0,AA,20889,2,2,0,2,2
1,AA,34009,1,1,0,1,1
2,AA,34031,2,2,0,2,2
3,AA,34039,1,1,0,1,1
4,AA,34092,1,1,0,1,1
5,AA,34093,1,1,0,1,1
6,AA,80913,1,1,0,1,1
7,AA,92055,1,1,0,1,1
8,AE,00000,1,1,0,1,1
9,AE,09009,1,1,0,1,1

In [110]:
# ============================================================
# SPECIALTY DIVERSITY
# ============================================================

geo_features["specialty_diversity_ratio"] = (
    geo_features["unique_specialty_count"]
    /
    geo_features["provider_count"]
)

geo_features["specialty_diversity_ratio"] = (
    geo_features["specialty_diversity_ratio"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

print(
    geo_features[
        [
            "STATE_CLEAN",
            "ZIP_CLEAN",
            "provider_count",
            "unique_specialty_count",
            "specialty_diversity_ratio"
        ]
    ].head(10)
)

  STATE_CLEAN ZIP_CLEAN  provider_count  unique_specialty_count  \
0          AA     20889               2                       2
1          AA     34009               1                       1
2          AA     34031               2                       2
3          AA     34039               1                       1
4          AA     34092               1                       1
5          AA     34093               1                       1
6          AA     80913               1                       1
7          AA     92055               1                       1
8          AE     00000               1                       1
9          AE     09009               1                       1

   specialty_diversity_ratio
0                        1.0
1                        1.0
2                        1.0
3                        1.0
4                        1.0
5                        1.0
6                        1.0
7                        1.0
8                        1.0
9                        1.0

In [111]:
# ============================================================
# STATE-LEVEL CONTEXT
# ============================================================

state_provider_totals = (
    geo_df
    .groupby("STATE_CLEAN")["NPI"]
    .nunique()
    .reset_index()
)

state_provider_totals = state_provider_totals.rename(
    columns={
        "NPI": "state_provider_count"
    }
)

geo_features = geo_features.merge(
    state_provider_totals,
    on="STATE_CLEAN",
    how="left"
)

geo_features["zip_provider_share_of_state"] = (
    geo_features["provider_count"]
    /
    geo_features["state_provider_count"]
)

print(
    geo_features[
        [
            "STATE_CLEAN",
            "ZIP_CLEAN",
            "provider_count",
            "state_provider_count",
            "zip_provider_share_of_state"
        ]
    ].head(10)
)

  STATE_CLEAN ZIP_CLEAN  provider_count  state_provider_count  \
0          AA     20889               2                    10
1          AA     34009               1                    10
2          AA     34031               2                    10
3          AA     34039               1                    10
4          AA     34092               1                    10
5          AA     34093               1                    10
6          AA     80913               1                    10
7          AA     92055               1                    10
8          AE     00000               1                   247
9          AE     09009               1                   247

   zip_provider_share_of_state
0                     0.200000
1                     0.100000
2                     0.200000
3                     0.100000
4                     0.100000
5                     0.100000
6                     0.100000
7                     0.100000
8                     0.004049
9                     0.004049

In [112]:
# ============================================================
# PROVIDER COMPOSITION
# ============================================================

geo_features["individual_provider_ratio"] = (
    geo_features["individual_provider_count"]
    /
    geo_features["provider_count"]
)

geo_features["organization_provider_ratio"] = (
    geo_features["organization_provider_count"]
    /
    geo_features["provider_count"]
)

geo_features[
    [
        "individual_provider_ratio",
        "organization_provider_ratio"
    ]
] = (
    geo_features[
        [
            "individual_provider_ratio",
            "organization_provider_ratio"
        ]
    ]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

print(
    geo_features[
        [
            "STATE_CLEAN",
            "ZIP_CLEAN",
            "provider_count",
            "individual_provider_ratio",
            "organization_provider_ratio"
        ]
    ].head(10)
)

  STATE_CLEAN ZIP_CLEAN  provider_count  individual_provider_ratio  \
0          AA     20889               2                        1.0
1          AA     34009               1                        1.0
2          AA     34031               2                        1.0
3          AA     34039               1                        1.0
4          AA     34092               1                        1.0
5          AA     34093               1                        1.0
6          AA     80913               1                        1.0
7          AA     92055               1                        1.0
8          AE     00000               1                        1.0
9          AE     09009               1                        1.0

   organization_provider_ratio
0                          0.0
1                          0.0
2                          0.0
3                          0.0
4                          0.0
5                          0.0
6                          0.0
7                          0.0
8                          0.0
9                          0.0

In [113]:
# ============================================================
# SAVE GEO FEATURE DATASET
# ============================================================

GEO_FEATURE_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/"
    "data/processed/"
    "provider_geo_features_zip.csv"
)

geo_features.to_csv(
    GEO_FEATURE_FILE,
    index=False
)

print("=" * 70)
print("GEOSPATIAL FEATURE DATASET SAVED")
print("=" * 70)

print(GEO_FEATURE_FILE)
print("Shape:", geo_features.shape)

======================================================================
GEOSPATIAL FEATURE DATASET SAVED
======================================================================
/content/drive/MyDrive/Provider_Network_Project/data/processed/provider_geo_features_zip.csv
Shape: (16934, 12)

In [ ]:
# ============================================================
# CHECK CURRENT GEOSPATIAL FEATURE DATASET
# ============================================================

import pandas as pd

GEO_FEATURE_FILE = (
    "/content/drive/MyDrive/Provider_Network_Project/"
    "data/processed/provider_geo_features_zip.csv"
)

geo_features = pd.read_csv(GEO_FEATURE_FILE)

print("=" * 70)
print("CURRENT GEO FEATURE DATASET")
print("=" * 70)

print("Shape:", geo_features.shape)

print("\nColumns:")
for col in geo_features.columns:
    print("-", col)

print("\nFirst 5 rows:")
display(geo_features.head())

======================================================================
CURRENT GEO FEATURE DATASET
======================================================================
Shape: (16934, 12)

Columns:
- STATE_CLEAN
- ZIP_CLEAN
- provider_count
- individual_provider_count
- organization_provider_count
- unique_specialty_count
- providers_with_specialty
- specialty_diversity_ratio
- state_provider_count
- zip_provider_share_of_state
- individual_provider_ratio
- organization_provider_ratio

First 5 rows:

In [ ]:
# ============================================================
# STEP 9 — DOWNLOAD CENSUS ZCTA POPULATION DATA
# NO API KEY REQUIRED
# ============================================================

import pandas as pd
import requests
from io import BytesIO
import zipfile
import os

print("=" * 70)
print("STEP 9 — CENSUS ZIP POPULATION DATA")
print("=" * 70)

# ------------------------------------------------------------
# Census downloadable ACS 2023 5-year ZIP/ZCTA population file
# ------------------------------------------------------------

url = (
    "https://www2.census.gov/programs-surveys/acs/"
    "summary_file/2023/table-based-SF/data/5YRData/"
    "acsdt5y2023-b01003.dat"
)

response = requests.get(url, timeout=120)

print("Status:", response.status_code)

if response.status_code != 200:
    print(response.text[:500])
    raise RuntimeError("Census population file download failed.")

print("Downloaded successfully.")

In [ ]:
# ============================================================
# STEP 9B — READ CENSUS B01003 POPULATION DATA
# ============================================================

import pandas as pd
import requests
from io import StringIO

print("=" * 70)
print("STEP 9B — READING CENSUS POPULATION DATA")
print("=" * 70)

# ------------------------------------------------------------
# Census B01003 file
# ------------------------------------------------------------

url = (
    "https://www2.census.gov/programs-surveys/acs/"
    "summary_file/2023/table-based-SF/data/5YRData/"
    "acsdt5y2023-b01003.dat"
)

response = requests.get(url, timeout=120)

print("Status:", response.status_code)

if response.status_code != 200:
    raise RuntimeError("Could not download Census population data.")

# ------------------------------------------------------------
# Inspect first few lines
# ------------------------------------------------------------

text = response.text

print("\nFirst 1000 characters:")
print(text[:1000])

In [ ]:
# ============================================================
# STEP 9C — EXTRACT ZCTA / ZIP POPULATION
# ============================================================

import pandas as pd
from io import StringIO

print("=" * 70)
print("STEP 9C — EXTRACTING ZCTA POPULATION")
print("=" * 70)

# ------------------------------------------------------------
# Read Census pipe-delimited data
# ------------------------------------------------------------

population_raw = pd.read_csv(
    StringIO(text),
    sep="|",
    dtype=str
)

print("Raw rows:", len(population_raw))
print("Raw columns:", population_raw.columns.tolist())

# ------------------------------------------------------------
# Keep required columns
# ------------------------------------------------------------

population_df = population_raw[
    ["GEO_ID", "B01003_E001"]
].copy()

# ------------------------------------------------------------
# Identify ZCTA records
# ------------------------------------------------------------
# ZCTA GEO_ID values are represented as:
#
# 8600000USXXXXX
#
# where XXXXX is the 5-digit ZCTA.
#
# ------------------------------------------------------------

zcta_mask = (
    population_df["GEO_ID"]
    .str.startswith("8600000US", na=False)
)

population_df = population_df[zcta_mask].copy()

print("\nZCTA rows:", len(population_df))

# ------------------------------------------------------------
# Extract 5-digit ZIP/ZCTA
# ------------------------------------------------------------

population_df["ZIP_CLEAN"] = (
    population_df["GEO_ID"]
    .str.replace("8600000US", "", regex=False)
    .str.zfill(5)
)

# ------------------------------------------------------------
# Rename population column
# ------------------------------------------------------------

population_df = population_df.rename(
    columns={
        "B01003_E001": "population"
    }
)

# ------------------------------------------------------------
# Convert population to numeric
# ------------------------------------------------------------

population_df["population"] = pd.to_numeric(
    population_df["population"],
    errors="coerce"
)

# ------------------------------------------------------------
# Keep final columns
# ------------------------------------------------------------

population_df = population_df[
    ["ZIP_CLEAN", "population"]
].copy()

# ------------------------------------------------------------
# Remove invalid population values
# ------------------------------------------------------------

population_df = population_df[
    population_df["population"].notna()
].copy()

# ------------------------------------------------------------
# Remove duplicate ZIPs
# ------------------------------------------------------------

population_df = population_df.drop_duplicates(
    subset=["ZIP_CLEAN"]
)

# ------------------------------------------------------------
# Reset index
# ------------------------------------------------------------

population_df = population_df.reset_index(drop=True)

# ------------------------------------------------------------
# Inspect
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CENSUS ZCTA POPULATION DATA")
print("=" * 70)

print("Rows:", len(population_df))
print("Columns:", population_df.columns.tolist())

print(
    "Population missing:",
    population_df["population"].isna().sum()
)

print(
    "ZIP missing:",
    population_df["ZIP_CLEAN"].isna().sum()
)

print("\nSample:")
display(population_df.head(10))

In [ ]:
# ============================================================
# STEP 9D — SAVE CENSUS POPULATION DATA
# ============================================================

POPULATION_FILE = (
    "/content/drive/MyDrive/Provider_Network_Project/"
    "data/processed/census_zip_population_2023.csv"
)

population_df.to_csv(
    POPULATION_FILE,
    index=False
)

print("=" * 70)
print("CENSUS POPULATION DATA SAVED")
print("=" * 70)

print(POPULATION_FILE)
print("Shape:", population_df.shape)

In [ ]:
# ============================================================
# STEP 9E — INSPECT CENSUS GEO_ID STRUCTURE
# ============================================================

print("=" * 70)
print("STEP 9E — INSPECTING GEO_ID VALUES")
print("=" * 70)

# Show GEO_ID values containing "US"
geo_ids = population_raw["GEO_ID"].dropna().astype(str)

print("Total GEO_ID values:", len(geo_ids))

print("\nExamples containing 'US':")
display(
    geo_ids[
        geo_ids.str.contains("US", na=False)
    ].head(50)
)

print("\nUnique GEO_ID prefixes:")
print(
    geo_ids.str[:15].value_counts().head(30)
)

In [ ]:
# ============================================================
# STEP 9F — CHECK FOR ZCTA RECORDS
# ============================================================

print("=" * 70)
print("STEP 9F — CHECKING FOR ZCTA RECORDS")
print("=" * 70)

zcta_rows = population_raw[
    population_raw["GEO_ID"]
    .astype(str)
    .str.startswith("8600000US")
].copy()

print("ZCTA rows found:", len(zcta_rows))

print("\nFirst 10 ZCTA records:")
display(zcta_rows.head(10))

print("\nExample ZCTA GEO_ID values:")
print(
    zcta_rows["GEO_ID"]
    .head(20)
    .tolist()
)

In [ ]:
# ============================================================
# STEP 9G — FIND CENSUS ZCTA RECORDS
# ============================================================

print("=" * 70)
print("STEP 9G — SEARCHING FOR ZCTA GEOGRAPHIES")
print("=" * 70)

geo_ids = population_raw["GEO_ID"].astype(str)

# Search for GEO_IDs containing 860
zcta_candidates = population_raw[
    geo_ids.str.contains("860", na=False)
].copy()

print("Rows containing '860':", len(zcta_candidates))

print("\nSample:")
display(zcta_candidates.head(20))

In [ ]:
# ============================================================
# STEP 9H — CHECK GEO_ID PATTERNS
# ============================================================

print("=" * 70)
print("GEO_ID PATTERN CHECK")
print("=" * 70)

print("\nFirst 100 GEO_ID values:")
print(
    population_raw["GEO_ID"]
    .head(100)
    .tolist()
)

print("\nGEO_ID values containing '860':")

print(
    population_raw[
        population_raw["GEO_ID"]
        .astype(str)
        .str.contains("860", na=False)
    ]["GEO_ID"]
    .head(50)
    .tolist()
)

In [ ]:
# ============================================================
# STEP 9A — FIND DOWNLOADED CENSUS FILE
# ============================================================

import glob
import os

CENSUS_DIR = "/content/drive/MyDrive/Provider_Network_Project/data/raw/census"

files = glob.glob(CENSUS_DIR + "/*")

print("Files found:")
for f in files:
    print(os.path.basename(f))

In [ ]:
# ============================================================
# STEP 9B — INSPECT CENSUS CSV
# ============================================================

import pandas as pd
import glob
import os

csv_files = glob.glob(CENSUS_DIR + "/*.csv")

print("CSV files found:", len(csv_files))

for f in csv_files:
    print(os.path.basename(f))

if len(csv_files) == 0:
    raise FileNotFoundError(
        "No Census CSV found. Upload the downloaded Census CSV "
        "to data/raw/census/"
    )

CENSUS_FILE = csv_files[0]

census_raw = pd.read_csv(
    CENSUS_FILE,
    low_memory=False
)

print("\nShape:", census_raw.shape)

print("\nColumns:")
print(census_raw.columns.tolist())

print("\nFirst 5 rows:")
display(census_raw.head())

In [ ]:
# ============================================================
# STEP 9 FINAL — CREATE CLEAN ZCTA POPULATION DATASET
# ============================================================

import pandas as pd
import os

print("=" * 70)
print("STEP 9 — CLEAN 2023 ACS ZCTA POPULATION")
print("=" * 70)

# ------------------------------------------------------------
# INPUT
# ------------------------------------------------------------

CENSUS_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/raw/census/"
    "ACSDT5Y2023.B01003-Data.csv"
)

# ------------------------------------------------------------
# READ FILE
# ------------------------------------------------------------

census_raw = pd.read_csv(
    CENSUS_FILE,
    low_memory=False
)

print("Raw shape:", census_raw.shape)

# ------------------------------------------------------------
# REMOVE FIRST METADATA ROW
# ------------------------------------------------------------
# Your first row contains:
# Geography | Geographic Area Name | Estimate!!Total | ...
# ------------------------------------------------------------

census_raw = census_raw.iloc[1:].copy()

# ------------------------------------------------------------
# CREATE CLEAN DATAFRAME
# ------------------------------------------------------------

population_df = pd.DataFrame()

# GEO_ID example:
# 860Z200US00601
# 860Z200US00602

population_df["ZIP_CLEAN"] = (
    census_raw["GEO_ID"]
    .astype(str)
    .str.extract(r"(\d{5})$")[0]
)

# Population estimate
population_df["population"] = pd.to_numeric(
    census_raw["B01003_001E"],
    errors="coerce"
)

# ------------------------------------------------------------
# REMOVE INVALID RECORDS
# ------------------------------------------------------------

population_df = population_df.dropna(
    subset=["ZIP_CLEAN", "population"]
)

population_df["ZIP_CLEAN"] = (
    population_df["ZIP_CLEAN"]
    .astype(str)
    .str.zfill(5)
)

population_df["population"] = (
    population_df["population"]
    .astype(int)
)

# Remove duplicates
population_df = population_df.drop_duplicates(
    subset=["ZIP_CLEAN"]
)

population_df = population_df.reset_index(drop=True)

# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CLEAN POPULATION DATA")
print("=" * 70)

print("Rows:", len(population_df))
print("Columns:", population_df.columns.tolist())

print(
    "Missing ZIP:",
    population_df["ZIP_CLEAN"].isna().sum()
)

print(
    "Missing population:",
    population_df["population"].isna().sum()
)

print(
    "Duplicate ZIPs:",
    population_df["ZIP_CLEAN"].duplicated().sum()
)

print("\nSample:")
display(population_df.head(10))

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

POPULATION_OUTPUT = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "census_zip_population_2023.csv"
)

population_df.to_csv(
    POPULATION_OUTPUT,
    index=False
)

print("\nSaved:")
print(POPULATION_OUTPUT)

In [ ]:
# ============================================================
# STEP 10 — MERGE PROVIDER FEATURES WITH POPULATION
# ============================================================

import pandas as pd

print("=" * 70)
print("STEP 10 — MERGING PROVIDER + POPULATION DATA")
print("=" * 70)

# ------------------------------------------------------------
# FILES
# ------------------------------------------------------------

PROVIDER_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "provider_geo_features_zip.csv"
)

POPULATION_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "census_zip_population_2023.csv"
)

# ------------------------------------------------------------
# LOAD
# ------------------------------------------------------------

provider_df = pd.read_csv(
    PROVIDER_FILE,
    dtype={
        "STATE_CLEAN": str,
        "ZIP_CLEAN": str
    }
)

population_df = pd.read_csv(
    POPULATION_FILE,
    dtype={
        "ZIP_CLEAN": str
    }
)

# ------------------------------------------------------------
# STANDARDIZE ZIP
# ------------------------------------------------------------

provider_df["ZIP_CLEAN"] = (
    provider_df["ZIP_CLEAN"]
    .astype(str)
    .str.zfill(5)
)

population_df["ZIP_CLEAN"] = (
    population_df["ZIP_CLEAN"]
    .astype(str)
    .str.zfill(5)
)

# ------------------------------------------------------------
# MERGE
# ------------------------------------------------------------

merged_df = provider_df.merge(
    population_df,
    on="ZIP_CLEAN",
    how="left",
    validate="many_to_one"
)

# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

print("\nProvider rows:", len(provider_df))
print("Population rows:", len(population_df))
print("Merged rows:", len(merged_df))

print("\nPopulation matched:",
      merged_df["population"].notna().sum())

print("Population missing:",
      merged_df["population"].isna().sum())

match_rate = (
    merged_df["population"].notna().mean() * 100
)

print(
    f"Population match rate: {match_rate:.2f}%"
)

print("\nSample:")
display(merged_df.head(10))

In [ ]:
# ============================================================
# ZIP + SPECIALTY DENSITY FEATURES
# ============================================================

# Create stable area identifier for API integration
area_specialty_features["area_id"] = (
    area_specialty_features["STATE_CLEAN"].astype(str)
    + "_"
    + area_specialty_features["ZIP_CLEAN"].astype(str)
)

area_specialty_features = area_specialty_features.merge(
    population_df,
    on="ZIP_CLEAN",
    how="left",
    validate="many_to_one"
)

area_specialty_features["specialty_provider_density_per_1000"] = np.where(
    area_specialty_features["population"] > 0,
    (
        area_specialty_features["specialty_provider_count"]
        / area_specialty_features["population"]
    ) * 1000,
    np.nan
)

print("=" * 70)
print("ZIP + SPECIALTY DENSITY FEATURES")
print("=" * 70)

print("Shape:", area_specialty_features.shape)

display(
    area_specialty_features[
        [
            "area_id",
            "STATE_CLEAN",
            "ZIP_CLEAN",
            "PRIMARY_TAXONOMY",
            "specialty_provider_count",
            "population",
            "specialty_provider_density_per_1000"
        ]
    ].head(20)
)

In [ ]:
# ============================================================
# SAVE ZIP + SPECIALTY FEATURE DATASET
# ============================================================

specialty_output_path = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "provider_network_ml_ready_specialty.csv"
)

area_specialty_features.to_csv(
    specialty_output_path,
    index=False
)

print("=" * 70)
print("ZIP + SPECIALTY DATASET SAVED")
print("=" * 70)

print("File:", specialty_output_path)
print("Shape:", area_specialty_features.shape)

In [ ]:
# ============================================================
# STEP 11 — PROVIDER DENSITY FEATURES
# ============================================================

import numpy as np

print("=" * 70)
print("STEP 11 — PROVIDER DENSITY")
print("=" * 70)

# ------------------------------------------------------------
# PROVIDERS PER 10,000 PEOPLE
# ------------------------------------------------------------

merged_df["providers_per_10000"] = np.where(
    merged_df["population"] > 0,
    (
        merged_df["provider_count"]
        / merged_df["population"]
    ) * 10000,
    np.nan
)

# ------------------------------------------------------------
# INDIVIDUAL PROVIDERS PER 10,000
# ------------------------------------------------------------

merged_df["individual_providers_per_10000"] = np.where(
    merged_df["population"] > 0,
    (
        merged_df["individual_provider_count"]
        / merged_df["population"]
    ) * 10000,
    np.nan
)

# ------------------------------------------------------------
# ORGANIZATION PROVIDERS PER 10,000
# ------------------------------------------------------------

merged_df["organization_providers_per_10000"] = np.where(
    merged_df["population"] > 0,
    (
        merged_df["organization_provider_count"]
        / merged_df["population"]
    ) * 10000,
    np.nan
)

# ------------------------------------------------------------
# INSPECT
# ------------------------------------------------------------

print("\nNew columns:")

print(
    [
        "population",
        "providers_per_10000",
        "individual_providers_per_10000",
        "organization_providers_per_10000"
    ]
)

display(
    merged_df[
        [
            "STATE_CLEAN",
            "ZIP_CLEAN",
            "provider_count",
            "population",
            "providers_per_10000",
            "individual_providers_per_10000",
            "organization_providers_per_10000"
        ]
    ].head(20)
)

In [ ]:
# ============================================================
# STEP 12 — FINAL ML-READY DATASET
# ============================================================

FINAL_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "provider_network_ml_ready.csv"
)

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

merged_df.to_csv(
    FINAL_FILE,
    index=False
)

print("=" * 70)
print("FINAL ML-READY DATASET")
print("=" * 70)

print("File:")
print(FINAL_FILE)

print("\nShape:")
print(merged_df.shape)

print("\nColumns:")
for i, col in enumerate(merged_df.columns, 1):
    print(f"{i}. {col}")

print("\nMissing values:")
display(
    merged_df.isna().sum()
)

print("\nFirst 10 rows:")
display(
    merged_df.head(10)
)

In [ ]:
# ============================================================
# STEP 13 — INVESTIGATE MISSING POPULATION
# ============================================================

print("=" * 70)
print("STEP 13 — POPULATION MATCH ANALYSIS")
print("=" * 70)

missing_population = merged_df[
    merged_df["population"].isna()
].copy()

print("Total provider ZIP rows:", len(merged_df))

print(
    "Population matched:",
    merged_df["population"].notna().sum()
)

print(
    "Population missing:",
    merged_df["population"].isna().sum()
)

print(
    "Population match rate:",
    f"{merged_df['population'].notna().mean() * 100:.2f}%"
)

print("\nMissing population by STATE:")

missing_by_state = (
    missing_population
    .groupby("STATE_CLEAN")
    .agg(
        missing_zip_rows=("ZIP_CLEAN", "count"),
        provider_count=("provider_count", "sum")
    )
    .sort_values(
        "missing_zip_rows",
        ascending=False
    )
)

display(missing_by_state)

In [ ]:
# ============================================================
# STEP 14 — UNMATCHED ZIP INSPECTION
# ============================================================

print("=" * 70)
print("UNMATCHED ZIP CODES")
print("=" * 70)

unmatched_zips = (
    missing_population[
        [
            "STATE_CLEAN",
            "ZIP_CLEAN",
            "provider_count"
        ]
    ]
    .sort_values(
        ["STATE_CLEAN", "ZIP_CLEAN"]
    )
)

print("Unmatched rows:", len(unmatched_zips))

display(
    unmatched_zips.head(100)
)

In [ ]:
# ============================================================
# STEP 15 — ML-1 DATA QUALITY SUMMARY
# ============================================================

total_rows = len(merged_df)

population_matched = merged_df["population"].notna().sum()

population_missing = merged_df["population"].isna().sum()

population_match_rate = (
    population_matched / total_rows * 100
)

density_available = merged_df[
    "providers_per_10000"
].notna().sum()

density_missing = merged_df[
    "providers_per_10000"
].isna().sum()

print("=" * 70)
print("ML-1 DATA QUALITY SUMMARY")
print("=" * 70)

print(f"Total ZIP-provider rows:       {total_rows:,}")
print(f"Population matched:            {population_matched:,}")
print(f"Population missing:            {population_missing:,}")
print(f"Population match rate:         {population_match_rate:.2f}%")
print(f"Density available:             {density_available:,}")
print(f"Density missing:               {density_missing:,}")
print(f"Final feature count:           {merged_df.shape[1]}")

In [ ]:
# ============================================================
# FINAL ML-1 VALIDATION
# ============================================================

FINAL_FILE = (
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "provider_network_ml_ready.csv"
)

final_df = pd.read_csv(FINAL_FILE)

print("=" * 70)
print("FINAL ML-1 VALIDATION")
print("=" * 70)

print("Shape:", final_df.shape)

print("\nDuplicate rows:", final_df.duplicated().sum())

print("\nMissing values:")
print(final_df.isna().sum())

print("\nNumeric summary:")
display(final_df.describe())

print("\nSample:")
display(final_df.head())

In [ ]:
# ============================================================
# ML-1 FINAL EDA
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(
    "/content/drive/MyDrive/"
    "Provider_Network_Project/data/processed/"
    "provider_network_ml_ready.csv"
)

print("=" * 70)
print("ML-1 FINAL EDA")
print("=" * 70)

print("Shape:", df.shape)

# ------------------------------------------------------------
# 1. Basic statistics
# ------------------------------------------------------------

print("\nProvider count statistics:")
print(df["provider_count"].describe())

print("\nSpecialty count statistics:")
print(df["unique_specialty_count"].describe())

print("\nPopulation statistics:")
print(df["population"].describe())

print("\nProvider density statistics:")
print(df["providers_per_10000"].describe())

In [ ]:
plt.figure(figsize=(10, 5))

plt.hist(
    df["provider_count"],
    bins=50
)

plt.xlabel("Provider Count")
plt.ylabel("Number of ZIP Areas")
plt.title("Provider Count Distribution")

plt.show()

In [ ]:
import numpy as np

density = df["providers_per_10000"].dropna()

plt.figure(figsize=(10, 5))

plt.hist(
    np.log1p(density),
    bins=50
)

plt.xlabel("log(1 + Providers per 10,000)")
plt.ylabel("Number of ZIP Areas")
plt.title("Provider Density Distribution")

plt.show()

In [ ]:
plt.figure(figsize=(10, 5))

plt.hist(
    df["specialty_diversity_ratio"],
    bins=30
)

plt.xlabel("Specialty Diversity Ratio")
plt.ylabel("Number of ZIP Areas")
plt.title("Specialty Diversity Distribution")

plt.show()

In [ ]:
plt.figure(figsize=(10, 5))

plt.hist(
    df["population"].dropna(),
    bins=50
)

plt.xlabel("Population")
plt.ylabel("Number of ZIP Areas")
plt.title("Population Distribution")

plt.show()

In [ ]:
import pandas as pd

data_dictionary = {
    "STATE_CLEAN": "Standardized provider state or territory code",
    "ZIP_CLEAN": "Five-digit ZIP/ZCTA identifier",
    "provider_count": "Total providers associated with the ZIP",
    "individual_provider_count": "Number of individual providers",
    "organization_provider_count": "Number of organization providers",
    "unique_specialty_count": "Number of distinct provider specialties in the ZIP",
    "providers_with_specialty": "Number of providers with available specialty information",
    "specialty_diversity_ratio": "Specialty diversity relative to total providers",
    "state_provider_count": "Total providers within the state or territory",
    "zip_provider_share_of_state": "Share of state or territory providers located in the ZIP",
    "individual_provider_ratio": "Proportion of providers that are individuals",
    "organization_provider_ratio": "Proportion of providers that are organizations",
    "population": "2023 ACS 5-year ZCTA total population",
    "providers_per_10000": "Providers per 10,000 population",
    "individual_providers_per_10000": "Individual providers per 10,000 population",
    "organization_providers_per_10000": "Organization providers per 10,000 population"
}

dictionary_df = pd.DataFrame(
    list(data_dictionary.items()),
    columns=["Feature", "Description"]
)

dictionary_path = (
    "/content/drive/MyDrive/Provider_Network_Project/"
    "data/processed/ML1_data_dictionary.csv"
)

dictionary_df.to_csv(dictionary_path, index=False)

print("Data dictionary saved:")
print(dictionary_path)

display(dictionary_df)

In [ ]:
summary = """
# ML-1 DATA ENGINEERING SUMMARY

Project:
Provider Network Adequacy and Access Intelligence

Role:
ML-1 - Data Engineering and Geospatial Feature Engineering

## Final Dataset

File:
provider_network_ml_ready.csv

Rows:
16,934

Features:
16

Duplicate rows:
0

## Data Pipeline

NPPES Provider Data
        ↓
Sampling
        ↓
Cleaning
        ↓
Provider aggregation
        ↓
Specialty feature engineering
        ↓
ZIP-level geographic aggregation
        ↓
2023 ACS ZCTA population integration
        ↓
Provider density calculation
        ↓
EDA
        ↓
ML-ready dataset

## Main Features

- Provider count
- Individual provider count
- Organization provider count
- Unique specialty count
- Specialty diversity
- State provider count
- ZIP share of state providers
- Individual/organization ratios
- Population
- Providers per 10,000 population
- Individual providers per 10,000 population
- Organization providers per 10,000 population

## Population Matching

Total provider ZIP records:
16,934

Population matched:
16,202

Population missing:
732

Population match rate:
95.68%

Density values available:
16,135

Density values missing:
799

## Missing Data Strategy

Unmatched population values were retained as missing values.

Missing population was NOT replaced with zero because
an unmatched Census ZCTA does not imply zero population.

## Important Limitations

1. NPPES was sampled rather than processed in its entirety.
2. The sample should not be interpreted as the complete US provider network.
3. ZIP codes and Census ZCTAs are not identical geographic concepts.
4. Some NPPES records contain special/territory/military-style addresses.
5. Provider density contains extreme values in low-population areas.
6. Provider count does not directly represent provider capacity,
   appointment availability, quality, or actual access.
7. Final access-gap target definition is owned by ML-2/other project members.

## EDA

Five EDA visualizations were generated:

1. Provider count distribution
2. Provider density distribution
3. Specialty diversity distribution
4. Population distribution
5. Additional provider/geographic feature analysis

## Handoff

Primary file:
provider_network_ml_ready.csv

Supporting files:
provider_geo_features_zip.csv
census_zip_population_2023.csv
ML1_data_dictionary.csv

ML-2 can use provider_network_ml_ready.csv as the feature dataset
for downstream target creation and model development.
"""

summary_path = (
    "/content/drive/MyDrive/Provider_Network_Project/"
    "data/processed/ML1_summary.txt"
)

with open(summary_path, "w") as f:
    f.write(summary)

print("ML-1 summary saved:")
print(summary_path)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!git clone https://github.com/geraldineamalor/provider-network-adequacy-intelligence.git

In [ ]:
%cd /content/provider-network-adequacy-intelligence

In [ ]:
!git checkout feature/ml1-data

In [ ]:
!ls

In [ ]:
!find "/content/drive/MyDrive/Provider_Network_Project" -maxdepth 3 -type f

In [ ]:
!du -h "/content/drive/MyDrive/Provider_Network_Project/data/raw/nppes_sample_300000.csv"
!du -h "/content/drive/MyDrive/Provider_Network_Project/data/processed/"*
!du -h "/content/drive/MyDrive/Provider_Network_Project/notebooks/ML1_provider_pipeline.ipynb"

In [ ]:
# Go to the cloned GitHub repository
%cd /content/provider-network-adequacy-intelligence

# Create folders if they don't exist
!mkdir -p data/processed
!mkdir -p ml
!mkdir -p docs

# Copy ML-1 notebook
!cp "/content/drive/MyDrive/Provider_Network_Project/notebooks/ML1_provider_pipeline.ipynb" \
   "ml/ML1_provider_pipeline.ipynb"

# Copy final ML-ready dataset
!cp "/content/drive/MyDrive/Provider_Network_Project/data/processed/provider_network_ml_ready.csv" \
   "data/processed/provider_network_ml_ready.csv"

# Copy supporting geographic features
!cp "/content/drive/MyDrive/Provider_Network_Project/data/processed/provider_geo_features_zip.csv" \
   "data/processed/provider_geo_features_zip.csv"

# Copy Census population data
!cp "/content/drive/MyDrive/Provider_Network_Project/data/processed/census_zip_population_2023.csv" \
   "data/processed/census_zip_population_2023.csv"

# Copy data dictionary
!cp "/content/drive/MyDrive/Provider_Network_Project/data/processed/ML1_data_dictionary.csv" \
   "data/processed/ML1_data_dictionary.csv"

# Copy ML-1 summary
!cp "/content/drive/MyDrive/Provider_Network_Project/data/processed/ML1_summary.txt" \
   "data/processed/ML1_summary.txt"

print("\n===== ML FOLDER =====")
!ls -lh ml/

print("\n===== PROCESSED DATA =====")
!ls -lh data/processed/

In [ ]:
%cd /content/provider-network-adequacy-intelligence

documentation = """# ML-1 Data Engineering and Geospatial Feature Engineering

## Project
Provider Network Adequacy and Access Intelligence

## Role
ML-1: Data Engineering and Geospatial Feature Engineering

## Objective
Prepare a clean, aggregated, geographic and ML-ready dataset for downstream machine learning.

## Data Sources

### 1. NPPES NPI Registry
Used for provider information, provider type, specialty, state and ZIP code.

The full NPPES file is very large, so a 300,000-record working sample was used for the hackathon pipeline.

### 2. Census ACS 2023 5-Year
Used to obtain population estimates at the ZCTA/ZIP level.

Dataset:
B01003 - Total Population

## Pipeline

NPPES Provider Data
        ↓
Sampling
        ↓
Data Inspection
        ↓
Data Cleaning
        ↓
Provider Type Processing
        ↓
Specialty Processing
        ↓
ZIP/State Standardization
        ↓
ZIP-Level Provider Aggregation
        ↓
Census Population Integration
        ↓
Provider Density Features
        ↓
EDA
        ↓
ML-Ready Dataset

## Sampling

A 300,000-record sample of NPPES was used because the complete NPPES monthly file is several GB in size.

The sampling approach was selected to make the pipeline practical to execute in Google Colab.

Important limitation:
The resulting dataset should be considered a hackathon working dataset and is not guaranteed to represent the complete US provider network.

## Geographic Feature Engineering

Providers were aggregated at ZIP level.

Generated geographic/provider features include:

- Provider count
- Individual provider count
- Organization provider count
- Unique specialty count
- Specialty diversity ratio
- State provider count
- ZIP share of state providers
- Individual provider ratio
- Organization provider ratio

## Population Integration

2023 Census ACS 5-Year ZCTA population data was joined using standardized ZIP/ZCTA identifiers.

Provider ZIP records: 16,934

Population matched: 16,202

Population match rate: 95.68%

Population records without a Census match: 732

Missing population values were retained as missing values and were NOT replaced with zero.

## Density Features

The following features were created:

- Providers per 10,000 population
- Individual providers per 10,000 population
- Organization providers per 10,000 population

Density features are calculated only where population is available and greater than zero.

## Final ML-Ready Dataset

File:

data/processed/provider_network_ml_ready.csv

Rows: 16,934

Features: 16

Duplicate rows: 0

## Final Features

1. STATE_CLEAN
2. ZIP_CLEAN
3. provider_count
4. individual_provider_count
5. organization_provider_count
6. unique_specialty_count
7. providers_with_specialty
8. specialty_diversity_ratio
9. state_provider_count
10. zip_provider_share_of_state
11. individual_provider_ratio
12. organization_provider_ratio
13. population
14. providers_per_10000
15. individual_providers_per_10000
16. organization_providers_per_10000

## EDA

Exploratory Data Analysis was performed on:

- Provider count distribution
- Provider density distribution
- Specialty diversity
- Population distribution
- Geographic/provider feature distributions

The distributions show strong skew in several provider and population-related variables.

## Important Limitations

1. NPPES data was sampled rather than using the complete provider registry.
2. ZIP code and Census ZCTA are related but are not exactly identical geographic concepts.
3. Some ZIP records do not have a matching Census population value.
4. Provider density can contain extreme values in areas with very small populations.
5. Provider count does not directly measure appointment availability, provider capacity, wait time or quality.
6. Target definition and final ML model selection are outside the ML-1 responsibility.

## Handoff to ML-2

The final ML-ready dataset is prepared for downstream:

- Target definition
- Feature selection
- Model development
- Model evaluation
- Provider access-gap prediction

ML-2 should consider appropriate handling of skewed density variables, including log transformation, robust scaling or winsorization where appropriate.

## Files

- ml/ML1_provider_pipeline.ipynb
- data/processed/provider_network_ml_ready.csv
- data/processed/provider_geo_features_zip.csv
- data/processed/census_zip_population_2023.csv
- data/processed/ML1_data_dictionary.csv
- data/processed/ML1_summary.txt

## Raw Data Policy

Large raw NPPES files and large intermediate files are intentionally not committed to GitHub.

They remain in Google Drive/local storage so that the GitHub repository remains lightweight.

"""

with open("docs/ML1_DATA_PIPELINE.md", "w") as f:
    f.write(documentation)

print("✅ ML-1 documentation created:")
print("docs/ML1_DATA_PIPELINE.md")

print("\n===== DOCUMENTATION =====")
!ls -lh docs/

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git add ml/ML1_provider_pipeline.ipynb
!git add docs/ML1_DATA_PIPELINE.md

!git add data/processed/provider_network_ml_ready.csv
!git add data/processed/provider_geo_features_zip.csv
!git add data/processed/census_zip_population_2023.csv
!git add data/processed/ML1_data_dictionary.csv
!git add data/processed/ML1_summary.txt

print("===== STAGED FILES =====")
!git status

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git status

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git commit -m "ML1: add provider data pipeline and geospatial features"

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git config --global user.name "Sushintha18"
!git config --global user.email "sushintha18@gmail.com"

In [ ]:
!git config --global user.name
!git config --global user.email

In [ ]:
!git commit -m "ML1: add provider data pipeline and geospatial features"

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git push origin feature/ml1-data

In [ ]:
import getpass
import os

github_username = input("Enter your GitHub username: ")
github_token = getpass.getpass("Enter your GitHub token: ")

os.environ["GITHUB_USERNAME"] = github_username
os.environ["GITHUB_TOKEN"] = github_token

print("Credentials received securely.")

In [ ]:
%cd /content/provider-network-adequacy-intelligence

# Create a temporary Git authentication helper
askpass_script = """#!/bin/sh
case "$1" in
  *Username*) echo "$GITHUB_USERNAME" ;;
  *Password*) echo "$GITHUB_TOKEN" ;;
esac
"""

with open("/tmp/git-askpass.sh", "w") as f:
    f.write(askpass_script)

!chmod 700 /tmp/git-askpass.sh

os.environ["GIT_ASKPASS"] = "/tmp/git-askpass.sh"
os.environ["GIT_TERMINAL_PROMPT"] = "0"

# Push your existing ML-1 commit
!git push origin feature/ml1-data

In [ ]:
%cd /content/provider-network-adequacy-intelligence
!git remote set-url origin https://github.com/Sushintha18/provider-network-adequacy-intelligence.git
!git remote -v

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git branch --show-current
!git log -1 --oneline
!git status

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git push -u origin feature/ml1-data

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git fetch origin
!git status
!git log --oneline --left-right HEAD...origin/feature/ml1-data

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git pull --rebase origin feature/ml1-data

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git checkout --ours ml/ML1_provider_pipeline.ipynb
!git add ml/ML1_provider_pipeline.ipynb

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git -c core.editor=true rebase --continue

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git status
!git log --oneline -3

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!git status
!git log -1 --oneline

In [ ]:
%cd /content/provider-network-adequacy-intelligence

!cp "/content/drive/MyDrive/Provider_Network_Project/data/processed/provider_network_ml_ready_specialty.csv" \
   "data/processed/provider_network_ml_ready_specialty.csv"

!git add data/processed/provider_network_ml_ready_specialty.csv

!git commit -m "ML1: add specialty-level provider dataset"

!git push origin feature/ml1-data